name: scidata-schema-validation

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: '*' 

jobs:

  linux:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install check-jsonschema

      - name: Run Unit schema validation
        run: |
          check-jsonschema -o json --schemafile schema/unit.json examples/sections/unit.jsonld

      - name: Run Value schema validation
        run: |
          check-jsonschema -o json --schemafile schema/value.json --instance examples/sections/value.jsonld
